GET http://localhost:8080/api/users
Accept: application/json

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "fullName": "Jane Doe"
}

###
POST http://localhost:8080/api/users/advertisement
Content-Type: application/json

{
  "userId": 71,
  "title": "Barackvirág"
}
